name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v0.1.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            artifact_name: KawaiiVoiceChanger-Linux
            build_name: KawaiiVoiceChanger
            package_ext: .tar.gz
            package_cmd: tar -czf
          - os: windows-latest
            name: Windows
            artifact_name: KawaiiVoiceChanger-Windows
            build_name: KawaiiVoiceChanger.exe
            package_ext: .zip
            package_cmd: 7z a -tzip
          - os: macos-latest
            name: macOS
            artifact_name: KawaiiVoiceChanger-macOS
            build_name: KawaiiVoiceChanger
            package_ext: .zip
            package_cmd: zip -r

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libportaudio2 libsndfile1

    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install portaudio libsndfile

    - name: Install project with build dependencies
      run: |
        uv sync --extra build

    - name: Build executable
      run: |
        uv run pyinstaller kawaii_voice_changer.spec --clean

    - name: List build output
      run: |
        ls -la dist/
      shell: bash

    - name: Create distribution package
      run: |
        cd dist
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          7z a -tzip ../${{ matrix.artifact_name }}${{ matrix.package_ext }} ${{ matrix.build_name }}
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          if [ -d "KawaiiVoiceChanger.app" ]; then
            zip -r ../${{ matrix.artifact_name }}${{ matrix.package_ext }} KawaiiVoiceChanger.app
          else
            zip -r ../${{ matrix.artifact_name }}${{ matrix.package_ext }} ${{ matrix.build_name }}
          fi
        else
          tar -czf ../${{ matrix.artifact_name }}${{ matrix.package_ext }} ${{ matrix.build_name }}
        fi
      shell: bash

    # Test binary before upload
    - name: Test binary startup (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        # Set up virtual display
        export DISPLAY=:99
        sudo apt-get install -y xvfb libegl1 libgl1 libxcb-xinerama0 libxcb-cursor0
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        
        # Test binary
        cd dist
        chmod +x ${{ matrix.build_name }}
        timeout 10s ./${{ matrix.build_name }} --help || EXIT_CODE=$?
        if [ "$EXIT_CODE" != "124" ] && [ "$EXIT_CODE" != "0" ]; then
          echo "Binary test failed with exit code: $EXIT_CODE"
          exit 1
        fi
        echo "Binary test passed"
      shell: bash

    - name: Test binary startup (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Test binary
        Start-Process -FilePath "./dist/${{ matrix.build_name }}" -ArgumentList "--help" -Wait -NoNewWindow -PassThru -ErrorAction SilentlyContinue | Out-Null
        
        # Quick startup test
        $process = Start-Process -FilePath "./dist/${{ matrix.build_name }}" -PassThru
        Start-Sleep -Seconds 5
        
        if ($process.HasExited -and $process.ExitCode -ne 0) {
          Write-Error "Binary test failed"
          exit 1
        }
        
        if (!$process.HasExited) {
          Stop-Process -Id $process.Id -Force
        }
      shell: powershell

    - name: Test binary startup (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Test binary
        if [ -d "dist/KawaiiVoiceChanger.app" ]; then
          timeout 10s ./dist/KawaiiVoiceChanger.app/Contents/MacOS/KawaiiVoiceChanger --help || EXIT_CODE=$?
        else
          timeout 10s ./dist/${{ matrix.build_name }} --help || EXIT_CODE=$?
        fi
        
        if [ "$EXIT_CODE" != "124" ] && [ "$EXIT_CODE" != "0" ]; then
          echo "Binary test failed"
          exit 1
        fi
      shell: bash

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}${{ matrix.package_ext }}

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
    
    - name: List artifacts
      run: |
        ls -la ./artifacts/
        ls -la ./artifacts/*/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: Release ${{ github.event.inputs.version || github.ref_name }}
        body: |
          # Kawaii Voice Changer ${{ github.event.inputs.version || github.ref_name }}
          
          ## 🎉 ダウンロード
          
          お使いのOSに対応したファイルをダウンロードしてください：
          
          - **Windows**: `KawaiiVoiceChanger-Windows.zip`
          - **macOS**: `KawaiiVoiceChanger-macOS.zip`
          - **Linux**: `KawaiiVoiceChanger-Linux.tar.gz`
          
          ## 📝 変更履歴
          
          詳細は[CHANGELOG.md](https://github.com/ayutaz/kawaii-voice-changer/blob/main/CHANGELOG.md)をご覧ください。
          
        files: |
          ./artifacts/KawaiiVoiceChanger-Windows/*.zip
          ./artifacts/KawaiiVoiceChanger-macOS/*.zip
          ./artifacts/KawaiiVoiceChanger-Linux/*.tar.gz
        draft: false
        prerelease: false